version: '3.8'

services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    environment:
      - APP_URL=http://localhost:8000
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_TOKEN=${DATABASE_TOKEN}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_TTL_MINUTES=${JWT_TTL_MINUTES}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - JWT_ISSUER=EscolaApi
      - JWT_AUDIENCE=EscolaApiUsers
    ports:
      - "${AUTH_SERVICE_PORT:-8000}:8000"
    networks:
      - app_network
    restart: unless-stopped

  backend-aspnet:
    build:
      context: ./Backend/Backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - TURSO_DATABASE_URL=https://escola-db-carlos9027.aws-us-west-2.turso.io
      - TURSO_AUTH_TOKEN=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3ODE2NDY5NDMsImlkIjoiMDE5ZWQyNmUtYmEwMS03ZjI2LTk0MTMtMWIwNmRhODY1MTBlIiwicmlkIjoiOWNkOTM0MTAtZjY4Ni00NWRlLTkwY2MtNWJmYjgyZjE2Y2U3In0.B7Lt_53wIDiQZvWpVerA70U_eOilpjwd5DW25s6YSqfVPDvhPB4DCX0fPY84fvg9n_rbQdFXfclsGurCPd2rCA
      - Jwt__Key=${JWT_SECRET:-UmaChaveMuitoSecretaComPeloMenos32Caracteres!}
      - Jwt__Issuer=EscolaApi
      - Jwt__Audience=EscolaApiUsers
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - auth-service
      - backend-aspnet
    environment:
      - PUBLIC_API_URL=${PUBLIC_API_URL:-http://localhost:8080}
      - PUBLIC_AUTHAPI_URL=${PUBLIC_AUTHAPI_URL:-http://localhost:8000}
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    networks:
      - app_network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    volumes:
    - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    - ./monitoring/grafana/dashboards:/etc/grafana/dashboards  # ← adicione essa linha no grafana
    ports:
      - "9090:9090"
    networks:
      - app_network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
  grafana_data: