FROM mcr.microsoft.com/dotnet/sdk:10.0-alpine AS builder
WORKDIR /app

# Copia e restaura as dependências
COPY *.csproj ./
RUN dotnet restore

# Copia o resto do código
COPY . ./

# ALTERAÇÃO AQUI: Garante que o publish limpe resquícios locais antes de buildar
RUN dotnet publish -c Release -o /app/publish --no-restore /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0-alpine
WORKDIR /app
COPY --from=builder /app/publish .
ENTRYPOINT ["dotnet", "Backend.dll"]