name: CI — Backend

on:
  push:
    branches: [main]
    paths:
      - "Backend/**"
  pull_request:
    branches: [main]
    paths:
      - "Backend/**"

defaults:
  run:
    working-directory: Backend

jobs:
  build:
    name: Restore & Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Test
        run: dotnet test EscolaApi.Tests/EscolaApi.Tests.csproj

  publish:
    name: Build & Push Container
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:          # <-- adicionado
      contents: read
      packages: write     # <-- permite publicar no ghcr.io

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: Backend/Backend
          file: Backend/Backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/backend:latest
            ghcr.io/${{ github.repository_owner }}/backend:${{ github.sha }}